version: "3.3"

services:

#  traefik:
#    image: traefik:1.5.4
#    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
#    ports:
#      #- "80:80"
#      - "8080:8080"
#      - "443:443"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ./conf/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
#      - /storage/data/traefik/acme:/etc/traefik/acme
#    labels:
#      - traefik.enable=false

  postgres:
    image: postgres:9.6
    restart: always
   # ports:
   #   - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ke*lf87_W6
    volumes:
#      - ./init:/docker-entrypoint-initdb.d
      - "/storage/data/postgres:/var/lib/postgresql/data"
    labels:
      - traefik.enable=false

  zeppelin:
    image: dmitryzagr/zeppelin:0.8.0-rc1-v2-spark2.2.0-hadoop3.0.2
    restart: always
    environment:
      - ZEPPELIN_LOG_DIR=/logs
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
      - ZEPPELIN_SERVER_CONTEXT_PATH=/zeppelin
      - ZEPPELIN_WEBSOCKET_MAX_TEXT_MESSAGE_SIZE=10240000
      - ZEPPELIN_MEM=-Xmx8192m -Xms8192m -XX:MaxPermSize=4096m
      - ZEPPELIN_INTP_MEM=-Xmx4096m -Xms4096m -XX:MaxPermSize=4096m
    ports:
      - 80:8080
    volumes:
      - ./conf/zeppelin/interpreter.json:/zeppelin/conf/interpreter.json
      - ./conf/zeppelin/conf/shiro.ini:/zeppelin/conf/shiro.ini
      - ./conf/zeppelin/conf/zeppelin-site.xml:/zeppelin/conf/zeppelin-site.xml
      - /storage/data/zeppelin/logs:/logs
      - /storage/data/zeppelin/notebook:/notebook
      - /root/data-unti:/zeppelin/input-data
    labels:
     - "traefik.backend=zeppelin"
     - "traefik.backend.loadbalancer.sticky=true"
     - "traefik.frontend.rule=PathPrefix:/zeppelin"
     - "traefik.enable=true"
     - "traefik.port=8080"
