apiVersion: v1
kind: Secret
metadata:
  name: hadoop-env
type: Opaque
data:
  HIVE_SITE_CONF_javax_jdo_option_ConnectionURL: amRiYzpwb3N0Z3Jlc3FsOi8vaGl2ZS1tZXRhc3RvcmUtcG9zdGdyZXNxbC9tZXRhc3RvcmU= #jdbc:postgresql://hive-metastore-postgresql/metastore
  HIVE_SITE_CONF_javax_jdo_option_ConnectionDriverName: b3JnLnBvc3RncmVzcWwuRHJpdmVy #org.postgresql.Driver
  HIVE_SITE_CONF_javax_jdo_option_ConnectionUserName: aGl2ZQ== #hive
  HIVE_SITE_CONF_javax_jdo_option_ConnectionPassword: aGl2ZQ== #hive
  HIVE_SITE_CONF_datanucleus_autoCreateSchema: ZmFsc2U= #false
  HIVE_SITE_CONF_hive_metastore_uris: dGhyaWZ0Oi8vaGl2ZS1tZXRhc3RvcmU6OTA4Mw== #thrift://hive-metastore:9083

  CORE_CONF_fs_defaultFS: aGRmczovL25hbWVub2RlOjgwMjA= #hdfs://namenode:8020
  CORE_CONF_hadoop_http_staticuser_user: cm9vdA== #root
  CORE_CONF_hadoop_proxyuser_hue_hosts: Kg== #*
  CORE_CONF_hadoop_proxyuser_hue_groups: Kg== #*

  HDFS_CONF_dfs_webhdfs_enabled: dHJ1ZQ== #true
  HDFS_CONF_dfs_permissions_enabled: ZmFsc2U= #false

  YARN_CONF_yarn_log___aggregation___enable: dHJ1ZQ== #true
  YARN_CONF_yarn_resourcemanager_recovery_enabled: dHJ1ZQ== #true
 # YARN_CONF_yarn_resourcemanager_store_class: org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
  YARN_CONF_yarn_resourcemanager_fs_state___store_uri: L3Jtc3RhdGU= #/rmstate
  YARN_CONF_yarn_nodemanager_remote___app___log___dir: L2FwcC1sb2dz #/app-logs
 # YARN_CONF_yarn_log_server_url: http://historyserver:8188/applicationhistory/logs/
  YARN_CONF_yarn_timeline___service_enabled: dHJ1ZQ== # true
  YARN_CONF_yarn_timeline___service_generic___application___history_enabled: dHJ1ZQ== #true
  YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled: dHJ1ZQ== #true
 # YARN_CONF_yarn_resourcemanager_hostname: resourcemanager
 # YARN_CONF_yarn_timeline___service_hostname: historyserver
 # YARN_CONF_yarn_resourcemanager_address: resourcemanager:8032
 # YARN_CONF_yarn_resourcemanager_scheduler_address: resourcemanager:8030
 # YARN_CONF_yarn_resourcemanager_resource__tracker_address: resourcemanager:8031
